### ISSUE TITLE
Using Pull Dog

### ISSUE THREAD

**Issue by ffMathy** [xtermi2/elasticsearch-searchguard#10]
Hi again, and thank you for making this great repository. You also helped me quite a bit recently, and I am thankful for that.

Now, I recently launched a service that I believe could be helpful in this repository. It's free to use, and I need feedback. I think it could really be a win-win for us both.

https://github.com/apps/pull-dog

It automatically spawns up a Docker-based test environment for each of your pull requests, based on a `docker-compose.yml` file that you choose.

I think it could be helpful in general, to test things out in production before they release.

What do you think?

**Comment by xtermi2** [comment]
Hi,
locks interesting, I will try it out.

**Comment by xtermi2** [comment]
Is there any related github rep or other issue site?
after first installing the githup app I got forwarded to:
https://dogger.io/pull-dog/install/github?code=e0975cd671dc336f2f6a&installation_id=8497821&setup_action=install
```json
{
"type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
"title": "An error occured while processing your request.",
"status": 500,
"traceId": "|65a3536-4fcdaedffef15e64."
}
```
Then I tried the "auto setup" by pushing a `pull-dog.json` and created a pull request:
- https://github.com/xtermi2/elasticsearch-searchguard/pull/11
- https://github.com/xtermi2/sec-elasticsearch-prometheus/pull/4
but on both repos nothing happens.

Then I tried to login at https://dogger.io/ and got this:
![image](https://user-images.githubusercontent.com/1821973/80723835-668d8400-8b01-11ea-8b2d-78132cef4c62.png)
Looks like I can see your repos and not mine.

**Comment by ffMathy** [comment]
Yeah I got the error report from the system itself 😫 

It could seem as if it happens because your GitHub user doesn't have an e-mail address. Is that the case? I actually thought that was a requirement for all GitHub profiles.

And yikes! Did not know that the repos of my setup were leaking into yours! Must be something with the GitHub client retrieving the wrong "installation ID". How embarrassing - I'll get that fixed right away.

So much for "works on my machine". Thank you for venturing into this, and I hope this doesn't keep you from continuing to try, once I have resolved the issues.

I'll let you know when it's all fixed. There's a 98% code coverage (and not just for coverage's sake - testing real things), but I must have missed these scenarios. Hard to test up against the GitHub API like this - I only have mocks in this part.

**Comment by ffMathy** [comment]
Oh, and do you have Discord or anything similar where I can contact you in more real-time?

**Comment by ffMathy** [comment]
I see you were installed now, but encountered issues (errors) during your pull request. I'll investigate.

**Comment by ffMathy** [comment]
It could look like it's failing because you have volumes in your compose file, which is not supported yet. I'll improve the error message and implement volume support when I get home.

Thanks once again for the patience.

**Comment by ffMathy** [comment]
#13 now contains the solution.
