### ISSUE TITLE
This is awesome - but what about an example?

### ISSUE THREAD

**Issue by ffMathy** [xtermi2/elasticsearch-searchguard#3]
This is awesome. Thank you.

Is there any way you could provide examples using `docker-compose` or `docker run` as one-liner commands you can fire off to fully test the setup?

**Comment by xtermi2** [comment]
There are already docker-compose examples:
- https://github.com/xtermi2/elasticsearch-searchguard/tree/master/example
  - Here you need to create your own certificats, this is described in the readme.md
- https://github.com/xtermi2/elasticsearch-searchguard/tree/master/src/test
  - This is the integration-test docker-compose. Just go to this directory an execute `sudo sysctl -w vm.max_map_count=262144; docker-compose up`. Maybe this is the one-liner you are searching for :)
