### ISSUE TITLE
Unable to download ulimit package - fatal error: sys/resource.h: No such file or directory

### ISSUE THREAD

**Issue by Durga275** [xtermi2/elasticsearch-searchguard#8]
> devtools::install_github("krlmlr/ulimit")
Downloading GitHub repo krlmlr/ulimit@master
√  checking for file 'C:\Users.\.\krlmlr-ulimit-67199f2/DESCRIPTION' (559ms)
-  preparing 'ulimit':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ulimit_0.0-3.tar.gz'
   
Installing package into ‘C:/Users/../R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ulimit' ...
** using staged installation
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c memsize.c -o memsize.o
memsize.c:2:26: fatal error: sys/resource.h: No such file or directory
 #include <sys/resource.h>
                          ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.1/etc/i386/Makeconf:208: memsize.o] Error 1
ERROR: compilation failed for package 'ulimit'
* removing 'C:/Users/../R/win-library/3.6/ulimit'
Error: Failed to install 'ulimit' from GitHub:
  (converted from warning) installation of package ‘C:/Users/../AppData/Local/Temp/RtmpAXvZdd/file1b8452ed2cf/ulimit_0.0-3.tar.gz’ had non-zero exit status
>

**Comment by xtermi2** [comment]
I have no idea what you're talking about. Maybe you posted to the wrong project?

**Comment by ffMathy** [comment]
Yeah this does indeed seem weird.

**Comment by Durga275** [comment]
I am sorry. I guess yes I did post in the wrong project. It is my first in Git hub.
