### ISSUE TITLE
Kibana issues

### ISSUE THREAD

**Issue by ffMathy** [xtermi2/elasticsearch-searchguard#9]
Originally cleaned up from #6, since that one now contains multiple issues that have been resolved.

My Kibana instance now gets this error:

> {"type":"log","@timestamp":"2020-04-08T10:30:49Z","tags":["warning","savedobjects-service"]
,"pid":6,"message":"Unable to connect to Elasticsearch. Error: [security_exception] no perm
issions for [indices:admin/get] and User [name=kibana, backend_roles=[kibana_user], request
edTenant=null]"}

Opening `https://<elasticurl>:9200` in the browser works with basic auth user "kibana" in the browser and the specified password, but my Kibana instance can't seem to access it either way.

If I fetch `GET https://<elasticurl>:9200/_cat/indices/*` I get:
```
green  open searchguard            Q8p5ioNFSrOhXTqUnm0__Q 1 0 7 0 29.7kb 29.7kb
yellow open .signals_settings      jZsKtX-lQQSKpjQR_Hgn_w 1 1 2 0  7.7kb  7.7kb
yellow open .signals_watches       rNeO4-U9Q3yQvV-I-l5CNA 1 1 0 0   283b   283b
yellow open .signals_accounts      8rj_TD-dQIGA8X9XOi80pA 1 1 0 0   283b   283b
yellow open .signals_watches_state s5OSLJ-xRZeJ-AqNwFoxLw 1 1 0 0   283b   283b
```

If I fetch `GET https://<elasticurl>:9200/searchguard/_search` I get:
```
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}
```

**Comment by ffMathy** [comment]
More logs from Kibana (before the error):

> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins-system"],"pid":6,
> "message":"Setting up [21] plugins: [usageCollection,metrics,timelion,apm_oss,uiActions,dat
> a,navigation,newsfeed,status_page,share,kibana_legacy,management,dev_tools,inspector,expres
> sions,visualizations,embeddable,dashboard_embeddable_container,home,eui_utils,bfetch]"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","usageCollection
> "],"pid":6,"message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","metrics"],"pid"
> :6,"message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","timelion"],"pid
> ":6,"message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","apm_oss"],"pid"
> :6,"message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","data"],"pid":6,
> "message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","share"],"pid":6
> ,"message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","home"],"pid":6,
> "message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","plugins","bfetch"],"pid":
> 6,"message":"Setting up plugin"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","savedobjects-service"],"p
> id":6,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before st
> arting saved objects migrations..."}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["info","savedobjects-service"],"p
> id":6,"message":"Starting saved objects migrations"}
> {"type":"log","@timestamp":"2020-04-08T11:10:34Z","tags":["warning","savedobjects-service"]
> ,"pid":6,"message":"Unable to connect to Elasticsearch. Error: [security_exception] no perm
> issions for [indices:admin/get] and User [name=kibana, backend_roles=[kibana_user], request
> edTenant=null]"}

**Comment by xtermi2** [comment]
As mentioned in https://github.com/xtermi2/elasticsearch-searchguard/issues/6 you have extracted your environment settings to `./env/kibana.env` can you please provide its content.
It should contain something like this:
```
ELASTICSEARCH_HOSTS=https://elasticsearch:9200
# "none" for easier handling of self signed certificates, otherwise you have to provide the used CA certificate in kibana.
ELASTICSEARCH_SSL_VERIFICATIONMODE=none
ELASTICSEARCH_USERNAME=kibana
ELASTICSEARCH_PASSWORD=somepassword
```
I've tried you docker-compose file with your settings, but used my certificate settings and elasticsearch.yml. Works fine. Here is everything packed together: 
[example.zip](https://github.com/xtermi2/elasticsearch-searchguard/files/4452428/example.zip)

**Comment by ffMathy** [comment]
It does indeed contain the above contents.

However, `kibana.env`'s permissions seem to be wrong. Will investigate and report back soon.

**Comment by xtermi2** [comment]
Maybe you should investigate in running docker without root: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
This could save you many of these permission issues - that's my experience.

**Comment by ffMathy** [comment]
Installing without root did not fix the problem. It turned out that everything was now configured correctly, but the instance did not have enough memory. 2 gigabytes is apparently not enough. It seems to need at least 3 - preferably 4.

Would be worth mentioning somewhere in case someone else has the same issue.

**Comment by xtermi2** [comment]
Ah, good to know. I will add something to the docu.

**Comment by ffMathy** [comment]
Yeah. You can also try it locally. If you locally restrict your Docker to only allow 2 GB, your "working" example will also fail 😄
